- versions.tf
The next major release might contain some changes that are not backwards compatible.
> Add version constraint for Terraform provider (hcloud)

- variables.tf
The Hetzner API token should not be exposed in case of any errors, as you can see at #8.
> Prevent secrets from being exposed

- providers.tf
terraform v1.1.4 (and at least v1.0.11) emits a warning for empty
provider blocks. Removing those still seems to work while avoiding
that warning.
> remove empty provider blocks

- agents.tf
- master.tf
- servers.tf
- variables.tf
Hi & thanks for this fantastic project!
I'd like to use a yubikey for authentication with my cluster, so I don't have a private ssh key lying on my disk, only on the token. The way that normally works is that I just use my local ssh-agent and pass the needed ssh identity as a *public* key to the agent. The following PR supports that workflow if private_key is set to `null`.
It currently duplicates the logic in 3 files to keep it simple, but I could also introduce `local.private_key` and `local.agent_identity` to deduplicate if you wish so.
What do you think, is this a viable approach?
> make private key optional to support hardware tokens for SSH

- main.tf
- templates/traefik_config.yaml.tpl
- variables.tf
The rationale for this PR has been documented in https://github.com/kube-hetzner/kube-hetzner/issues/18#issuecomment-1019993588. I believe that usage of kube-hetzner together with external-dns is broken without this settings - using cloudflare proxying just hides the issues, because cloudflare seems to filter the private IP automatically.
With this PR it should work both, with or without proxying as well as for other DNS providers supported by external-dns
> ingress: don't use private ip, make ipv6 optional

- main.tf
- terraform.tfvars.example
- variables.tf
Instead of hard-coding the network into `eu-central`, this allows the user to set the network region in the main config
> Use variable for network region

- agents.tf
- main.tf
- master.tf
- servers.tf
it is important to use placement group for HA deployment, from Hetzner Cloud doc they are used to influence the distribution of interdependent virtual servers in their data centers.
In spread placement groups, all virtual servers are running on different physical servers. This decreases the probability that some instances might fail together.
> Add Hetzner placement group and link servers to it

- locals.tf
- master.tf
- templates/config.ign.tpl
Use ignition file to set up eth1 and to set the hostname.
Also, change the aria2 installation from `apt` to `apt-get` because the latter doesn't use fancy terminal features that clutter terraform output.
> Configure eth1 and set hostname

- master.tf
the current implementation works co-incidentally for most
setups, when terraform apply is run from the repos root,
but not when kube-hetzner is used as a terraform module
> fix kubectl get nodes missing --kubeconfig

- agents.tf
- locals.tf
- master.tf
- servers.tf
Newly added ssh commands were missing the flag -i to pass an
identity file. This means that those commands use different
settings then the provisioners and their connection blocks
around them.
While adding this parameter, I decided it would be cleanest
to add local.ssh_args.
> fix ssh identity in staging

- templates/master_config.yaml.tpl
- templates/server_config.yaml.tpl
YAML syntax does not allow multiple fields with the same key; the last one overrides all the previous.
> Really disable servicelb

- templates/master_config.yaml.tpl
- templates/server_config.yaml.tpl
That is the expected status when you create a cluster with most of the deployment systems (i.e., kubeadm or kind)
Fix #39
> Taint control-plane nodes with node-role.kubernetes.io/master:NoSchedule

- agents.tf
- locals.tf
- servers.tf
Otherwise, when you scale the number of the servers, all the agents will change IP, and the load balancer will become confused.
> Agents IP should not depend on servers_num

- main.tf
- output.tf
Hi,
So this is not 100% percent solid, as data.hcloud_load_balancer depends on the load balancer being deployed quick enough after CCM deployment is started - but it worked for me in practice on three runs and I think it's really useful to have this external endpoint in terraforms output.
> Expose load balancer ip

- README.md
- examples/tls/ingress.yaml
- examples/tls/pod.yaml
- examples/tls/service.yaml
Here's  the tested documentation to quickly spin up an nginx pod with TLS, as asked here https://github.com/kube-hetzner/kube-hetzner/pull/37#issuecomment-1037554173
I'm just not sure about the subdomains part, I usually use one certificate per subdomain,
> Added documentation to use TLS with traefik

- init.tf
- kubeconfig.tf
- locals.tf
- main.tf
- modules/host/out.tf
- output.tf
- servers.tf
The first control plane node is now identical to any other server
node. The cluster initialization happens once in two steps: first, make
sure that the k3s cluster is initialized and then apply our
configurations while the other nodes join. This change makes the
initialization more resilient and even faster than before.
> First control plane node is not special anymore

- main.tf
- modules/host/locals.tf
Hey folks, this build-up on the good work of @phaer in previous commits.
It was achieved with a simple null resource that triggers on the change of the token, and my testing indicated that it's also necessary to delete the network.
The end result is that it works well and the destroy is smooth. Even in the case of an eventual error, it will continue, if the LB was not there for instance, or the hcloud command was not installed.
> Auto destroy LB on terraform destroy

- README.md
- examples/tls/ingress.yaml
This removes the secret from the TLS example. Otherwise you'll get errors that the secret does not exist, see #109.
> Remove secret from TLS example

- agents.tf
- control_planes.tf
- init.tf
- main.tf
- output.tf
- terraform.tfvars.example
- variables.tf
The automatic pet name for both the cluster and nodes felt like overkill and I did not feel comfortable with them. Now setting the cluster name manually makes more sense, as the cluster is here to stay, its name can be meaningful. As the random pets are really random and meaningless, that suits more the ephemeral nature of nodes.
It defaults to "k3s" but can be anything like "k3s-cluster-xyz" as long as it is hostname compatible. It has the right checks for that.
> Changed the cluster name to manual

- agents.tf
- control_planes.tf
- locals.tf
- main.tf
- terraform.tfvars.example
- variables.tf
Hey folks, the subnets did not need manual input. Potentially this would have been error-prone and could be simplified. I used [cirdsubnet](https://www.terraform.io/language/functions/cidrsubnet) to generate them automatically. It creates the same kind of subnets we previously defined, while reducing the number of lines in the code, and the work required on the part of the user.
> Automatic subnets creation

- .github/dependabot.yaml
- .github/release.yaml
- .github/workflows/publish-terraform.yaml
- .github/workflows/validate-terraform.yaml
- renovate.json
Hi,
This does 3 things:
* Switch from renovate to dependabot. I hadn't noticed that dependabot has become part of github, so I'd just use that one for updates. github actions and terraform modules are included. See [docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) or [my repo for an example of logs](https://github.com/phaer/kube-hetzner/network/updates).
* Use https://github.com/ncipollo/release-action to automatically generate a release whenever a tag is pushed. (the tag should **not** include a "v" prefix, as that one will be added by the action). Once our terraform registry project is set up, a webhook will be triggered upon release to upload the release to registry.terraform.io. 
* …
> automatically publish releases for tags, switch to dependabot

- templates/traefik_config.yaml.tpl
By default, if the helm chart installation or upgrade fails for any
reason, the whole helm chart is deleted and recreated from scratch,
with a new load balancer bound to a new IP.
By setting the traefik helm chart failure policy to `stop`, we prevent
the load balancer service from being recreated in case of chart
upgrade failure, at the cost of requiring manual user intervention to
restore automatic upgrades.
> Improve stability of traefik load balancer IP

- README.md
- agents.tf
- control_planes.tf
- init.tf
- locals.tf
- main.tf
- terraform.tfvars.example
This creates two groups of subnets, one for the agent and one for the nodepools; that way, the nodepools are a lot easier to scale.
Combined max 255 nodepools, with each 64k nodes. Should be enough to make everyone happy! :) 
Pardon my ugly drawing, but should make it simpler to understand:
> Network subnet dissociation

- templates/plans.yaml.tpl
Adds `tolerations` so that the system-upgrade job can run on the storage node.
fixes #181
> system-upgrade on the storage node

- .gitignore
- README.md
- kubeconfig.tf
- main.tf
Oh man, this took wayy too long to figure out - can only use `self` an `each.key` on destroy AND you need to specify those als triggers AND environment.
But it seems to be working now. Ofc if there is a better solution... ;)
relates to #190
> + use cluster_name as prefix for local kubeconfig.yaml

- agents.tf
- control_planes.tf
When I try to deploy a PVC with ReadWriteMany I get an error 
```
rpc error: code = Internal desc = mount failed: exit status 32 .... helper program, or other error
(for several filesystems (e.g. nfs, cifs) you might
need a /sbin/mount. helper program)
```
Therefore, I've added the `nfs-client` to our servers for supporting RWX mounts. This option is only enabled if Longhorn is enabled.
Relates to: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/184
> Added nfs-client package if Longhorn is enabled

- init.tf
- templates/ccm.yaml.tpl
This PR introduces the `LegacyNodeRoleBehavior=false` feature gate to the CCM to allow the Hetzner loadbalancer to point at schedulable controlplane nodes. I'm guarding the feature gate behind the `allow_scheduling_on_control_plane` setting, but if you feel that this is not necessary, I can drop the guard and set it as default for all new clusters.
Resolves https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/55.
> Allow Hetzner LB to point at schedulable controlplane nodes

- README.md
- agents.tf
- control_planes.tf
- init.tf
- kube.tf.example
- kubeconfig.tf
- kustomization_backup.tf
- locals.tf
- main.tf
- modules/host/locals.tf
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
- versions.tf
solves #167 #161
was a bit difficult to solve. It's not 100% clean either, but it does what it's supposed to. 
I tried both the way to create the ssh key via pipe & /dev/stdio and via a file created via terraform local_secret_file, which I then delete again. 
The first does not work because the rights must be set to 0600. 
The second is unattractive because changes are displayed on every rerun. 
I have now solved this so that the corresponding file is created under /tmp and then deleted again. The file is created with 0600, which I think should be acceptable from a security point of view.
> changed ssh keys from file to string.

- init.tf
- templates/ccm.yaml.tpl
Hi
This PR sets these two environments variables to the hcloud ccm. The settings are the same as for the treafik lb, but this way they are default values for the hole cluster. 
More informations about these env here: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md 
It is related to #175 .
> Set default lb location to hcloud ccm

- docs/terraform.md
- modules/host/main.tf
**Why**?
```
│ Warning: Argument is deprecated
│ 
│   with module.kube-hetzner.module.control_planes.random_string.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 5, in resource "random_string" "server":
│    5:   number  = false
│ 
│ Use numeric instead.
│ 
│ (and 11 more similar warnings elsewhere)
```
According to docs https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string 
**Effect**
Literally just changed "number" to "numeric"
> deprecation fix: changed number to numeric in host/main.tf

- README.md
- docs/terraform.md
- init.tf
- templates/ccm.yaml.tpl
- variables.tf
1. Setting `HCLOUD_LOAD_BALANCERS_ENABLED` for the Hetzner Cloud CCM to `false` when klipper LB is enabled, and otherwise to `true`.
- This fixes the problem of getting unneeded and not properly working Hetzner LBs on single node clusters, see #245 
1. The default for `load_balancer_type` was `cpx11` which is not a valid load balancer type. Set is to `lb11` like in `kube.tf.example`
- Keeping the LB type unset in the kube.tf got the deployment stuck at `Waiting for load-balancer to get an IP...` and the error `hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: load balancer type cpx11 not found (invalid_input)`
> Disable CCM Load Balancers when using Klipper, fix default LB type

- agents.tf
- control_planes.tf
- docs/terraform.md
- modules/host/main.tf
- modules/host/templates/userdata.yaml.tpl
- modules/host/variables.tf
- variables.tf
Hetzner as authorative DNS servers on their cloud servers that resolve
different IP addresses for some of their products, such as Storage Box,
when we overwrite them, we stop those services from being connectable
from Hetzner Cloud.
This change allows users to choose their own DNS Servers (or default to
the current Google/Cloudflare combo), or even provide an empty list and
use Hetzner.
Relates-to: #249
> Allow the dns to be configurable

- docs/terraform.md
- locals.tf
- variables.tf
When using some csi, such as the smb csi, you need additional packages
on the host nodes. Currently you need an additional null resource to
install these, and that will cause problems if autoscaling is ever
implemented. This change allows the user to specify additional packages
to include.
This has already been implemented in #244 however that seems to have
stalled, so this change reinstates the idea.
> Allow additional packages to be installed on the nodes

- agents.tf
- control_planes.tf
- docs/terraform.md
- init.tf
- kubeconfig.tf
- locals.tf
- variables.tf
Currently all incoming connections go to the first control-plane node.
This means that if kured is restarting that node, an API user can
experience downtime. This change loadbalances the incoming requests via
a loadbalancer, meaning the service never appears down.
To facilitate that, we also add a few new labels to resources to allow
for easy identification.
This also means the cluster will be highly available, as we can use the
loadbalancer rather than node IPs for the server ip address.
> Loadbalance control plane

- locals.tf
- templates/plans.yaml.tpl
This taint should match the new role name "control-plane"
Kubeadm [will remove this with 1.25][issue]. It's a bit of an awkward timing, because that looks like it will come out at the [end of this month](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25#summary)
[issue]: https://github.com/kubernetes/kubeadm/issues/2200
> Remove deprecated taint

- README.md
- agents.tf
- control_planes.tf
- docs/terraform.md
- init.tf
- kube.tf.example
- kubeconfig.tf
- kustomization_backup.tf
- locals.tf
- modules/host/main.tf
- modules/host/templates/userdata.yaml.tpl
- modules/host/variables.tf
- variables.tf
The use of alternative SSH port is useful for different use cases or
when we need to provide the port for other service.
Fixes: #277.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> Allow setting alternative SSH port for host access

- README.md
- init.tf
- kube.tf.example
- templates/longhorn.yaml.tpl
- variables.tf
I added two variables to accommodate my needs with mongodb (which strongly recommends the xfs file system). I imagine a better solution would be expanding PR #244 and allowing these options to be set during volume creation instead of as a global in the longhorn.yml file, but I wanted to get his out there regardless in case it does prove useful.
Thanks!
> Added longhorn variables for fstype and default replica count

- locals.tf
This fixes #270. 
@t1murl @PurpleBooth This turned out easier than I thought.
I tested by forcefully rebooting the nodes with a custom kured-config that checks every minute and manually touching /var/run/reboot-required.
Everything works as it is supposed to! Turns out only the agent nodes need the taint; I gather this from the name of the Cilium config, where we can specify the key "agent-not-ready-taint-key".
In the testing, I also tried the cilium cli, which also worked. But did not produce an optimal config out of the box, so choosing to remain with the HelmChart definition for now.
Please forgive the diff; it shows some changes but not too many, as I created the branch late. But at least you'll get an idea. 
Unless you folks find something, I will push out this long-awaited fix ASAP.
> Cilium fix

- README.md
- data.tf
- docs/terraform.md
- init.tf
- kube.tf.example
- locals.tf
- main.tf
- nginx_ingress_values.yaml.example
- output.tf
- rancher_values.yaml.example
- templates/nginx_ingress.yaml.tpl
- templates/rancher.yaml.tpl
- templates/traefik_config.yaml.tpl
- variables.tf
This PR adds the Nginx ingress controller and the possibility to use a helm `_values.yaml` file for both it and Rancher. It also tweaks the variable names to make them more consistent.
Last but not least, a lot of the logic related to load-balancers, including Klipper, has been tweaked and cleaned up!
This fixes #293.
> Add Nginx ingress controller + various tweaks | ⚠️ Breaking changes in some variable names

- agents.tf
- kube.tf.example
- locals.tf
- nginx_ingress_values.yaml.example
- templates/nginx_ingress.yaml.tpl
Changed from nginx-ingress to ingess-nginx, which was the intended version.
I also took the opportunity to fix a few tiny bugs in the creation of Longhorn volumes, no critical but present. Now fixed.
> Nginx-ingress to ingess-nginx

- README.md
- cilium_values.yaml.example
- control_planes.tf
- docs/ssh.md
- docs/terraform.md
- init.tf
- kube.tf.example
- locals.tf
- nginx_ingress_values.yaml.example
- output.tf
In response to #325 
This PR sets the external IP of the control planes to the `tis-san` for the certificate to prevent certificate errors on the first request to the Kubernetes API.
When the control plane load balancer is used, nothing should change. I tested it with 1 and 3 control planes and the connection to each cp works properly.
I'm still a bit unsure about `tls-san` in `control-planes.tf`, should it include only the IP of the current server or the list of all CP IPs?
> Set tls-san to external ip for control planes

- README.md
- extra-manifests/.gitkeep
- init.tf
- kube.tf.example
- kustomization_user.tf
- variables.tf
Following up to #328 this PR implements support for a user defined kustomization.
The extra step is triggered if `extra-manifests/kustomization.yaml.tpl` exists. 
It will be executed after `kustomization` was successful, so it can't break the cluster build.
If this step fails (e.g. `kubectl -k apply) the manifest can be fixed and run again, without rebuilding the cluster!
> Extra manifests

- variables.tf
Just a minor problem: the cluster name isn't allowed to contain a `0` which may cause problems with auto-generated names. 
It don't see any reason why the `0` should be excluded (correct me if im wrong)
> Allow `0` in cluster name

- modules/host/out.tf
- output.tf
Follow up to #332.
This adds 2 new outputs `ingress_public_ipv4` and `ingress_public_ipv6`.
They support `hetzner_lb` and `klipper` and are more consistent to use between single-node clusters with `klipper` and full blown clusters.
To be conservative I added them as new outputs instead of extending the existing `load_balancer_public_ipv4|6`.
Since I haven't experience with klipper setups a few questions remain: 
How to handle setups besides single-node clusters where it is save to assume the first control-plane accepts the traffic?
My best guess would be something like this: (just some rough code for understanding)
```
if(!local.using_kilpper_lb){
return  data.hcloud_load_balancer.cluster[0].ipv4
}
if(local.is_single_node_cluster){
return …
```
> Output the cp ip when using klipper

- data.tf
- init.tf
- locals.tf
- output.tf
Followup to #336
And this should be the final one!
- `ingress_public_ipv4` is now always populated, either with the lb ip or with the ip of the first control plane.
- `ingress_public_ipv6 ` is only populated when a load balancer is used and IPv6 is not disabled
This should clear #284!
> Ignore ingress config for ip outputs

- README.md
- agents.tf
- control_planes.tf
- kube.tf.example
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
This adds `automatically_upgrade_os` as an option to control the automatic system updates. 
As disabling them is needed for non HA clusters to work properly. This is far more convenient than the "ssh in each node" method described right now in the docs.
For convince it might be even better to set this automatically depended on the node counts, but it is contrasted by the security risk. There for I personally would tend to leaving it as user choice.
> Add switch to disable automatic os updates

- agents.tf
- control_planes.tf
I'm working with ~20-22 nodes and everytime, I re-created the whole cluster, it failed because of wrong placement_group mappings (it tried to map >10 nodes at one placement_group)
As far as I could calculate, the placement_group logic is starting one ID above 0 (1) and accidentally used the terraform overflow-logic (if n+1 is longer than the array-size, start from 0)
I think I solved it by slightly replace the calculation :-)
> Fix placement groups

- README.md
- docs/terraform.md
- init.tf
- kube.tf.example
- kubeconfig.tf
- kustomization_backup.tf
- main.tf
- variables.tf
Fixes #349 by removing the local kubeconfig file and documented how to export it from the terraform output
> Opt out of local files and add kubeconfig as an output to the kube.tf example

- kubeconfig.tf
closes: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/357
> Outputted `kubeconfig`: Abide to the `cluster_name` module input var

- agents.tf
- control_planes.tf
- data.tf
- kube.tf.example
- variables.tf
This allows setting a label selector to add the public ssh keys stored in the hetzner cloud to the provisioned machines.
I will update terraform docs later today.
@mysticaltech Would be great if you could take a look and maybe give it a try it if still works when no label is provided.
> Support adding ssh keys from hcloud by label

- modules/host/main.tf
This to deal with the fact that automatic location selection has become unreliable, as some sources have either blacklisted hetzner servers IPs or have corrupt images.
> Changed the image server location to a fixed DE server

- kube.tf.example
fixes an issue where an initial create was not possible is the default kube.tf.example was just used
> fix: use same datatype for default tf example

- init.tf
- kube.tf.example
- variables.tf
Closes #408 
Adds ability to have to custom config.yaml entries for the control planes, I'm not exactly sure if everything works.
`terraform validate` returns no errors, so please correct me if I made something wrong! I haven't actually tested it yet though
> Support custom configuration options for control planes

- agents.tf
- control_planes.tf
- docs/terraform.md
- kube.tf.example
- modules/host/main.tf
- modules/host/templates/userdata.yaml.tpl
- modules/host/variables.tf
- variables.tf
Hi and thanks for amazing project. 
I needed to connect my cluster to existing registries, but I couldn't find an option to do so. 
This is my attempt to create such option.
> Why don't you create this file on node startup?
Because if you change registries.yaml contents later we need to reload all k3s services on all nodes.
> Why do new resources depend on kustomization resource?
Because otherwise, when we create cluster for the first time and you provide custom registry config, the error may occur.
Since we need to restart k3s services after updating the config, it may create a conflict where kustomization target and new targets try to interact with k3s service at the same time.
I would really appreciate a feedback for this PR.
Signed-off-by: Pavel Kirilin <win10@list.ru>
> Added option to configure private registries.

- docs/terraform.md
- init.tf
- kube.tf.example
- templates/longhorn.yaml.tpl
- variables.tf
Hi and thanks for the great project.
Due to some tooling constraints I had to modify the namespace longhorn is deployed into.
Initially, this namespace is hardcoded in the deployment.yaml, so this is my attempt to make it configurable via kube.tf
I thought I ask if you might find this useful, but feel free to dismiss if such additions are not considered relevant.
Thanks,
morphine
> Adds option to modify longhorn namespace upon deployment

- kubeconfig.tf
When calling `terraform destroy` without an actual cluster, an error is raised because entry [0] is accessed on an empty list `module.control_planes`. This commit catches that.
> fix: destroy on empty state should work ok.

- data.tf
- locals.tf
A minor modification, but it seems that github can have issues which make this change useful: if versions of packages are fixed in user input (hetzner_ccm, hetzner_csi and kured), there is no need to ping github to retrieve the latest release numbers. This pull request implements the conditionality of the github_release calls.
> fix: avoid querying repos for latest version if versions are fixed.

- kubeconfig.tf
Apparently it can happen that Hetzner Cloud takes too long to setup on of the servers. In this case, terraform times out, and there is no ip in the state, even though the server exists. When terraform-destroying on that state, the ipv4 field may not exist and the destroy could fail. With this fix (building on a previous fix), that scenario now works.
> Fix/destroy on correct state of failed build.

- autoscaler-agents.tf
- kustomize/kured.yaml
- modules/host/main.tf
- templates/autoscaler-cloudinit.yaml.tpl
> Update `registries.yaml` on existing nodes

- agents.tf
- autoscaler-agents.tf
- control_planes.tf
- init.tf
- kube.tf.example
- kustomize/kured.yaml
- locals.tf
- main.tf
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
Closes:
- #469, fixes container pull errors.
- #467, brings multiple TLS-SANs.
- #461, brings the ability to set a custom mirror link for MicroOS.
- #447, fixes control plane nodes showing up in LB as targets when scheduling is not allowed.
- #436, fixes SSH extra rules merging, now done correctly.
> Multiple fixes

- init.tf
- kube.tf.example
- templates/longhorn.yaml.tpl
- variables.tf
The default repository from which longhorn is pullen, is a mirror from rancher. This assures compatibility with rancher. However, as it is a modified mirror, it can be behind in version compared to the upstream source longhorn.io. This PR adds an optional variable so you can point to longhorn.io.
Use case today: k3s v1.25 with longhorn 1.4 run perfectly fine together when you use the longhorn.io helm repository.
> feat: added variable for choosing repository for longhorn helm chart.

- README.md
- kube.tf.example
- modules/host/locals.tf
- modules/host/main.tf
- variables.tf
This fixes #528, by temporarily downgrading the `container-selinux` package, while we wait for the fix, most probably coming in the next version of `k3s-selinux`. See https://github.com/k3s-io/k3s-selinux/issues/36
Also, I lock the `container-selinux` package, so that an automatic upgrade, so not break the system.
Last but not least, this PR does small improvements, like switching back to the automatic mirror OpenSUSE MicroOS link, as previously suggested by @aleksasiriski, while preserving the known-working mirror link in the `kube.tf.example`.
> Emergency downgrade of the container-selinux package + tiny improvements

- autoscaler-agents.tf
- control_planes.tf
- init.tf
- locals.tf
- modules/host/main.tf
I chose not to make this an optional thing, avoiding adding variables. Only merge this branch if tests show that it is a good idea. Otherwise modify the code to make wireguard optional. See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/527
I do not know all the arguments for and against making this standard, so I am marking this MR as draft and hope to see some discussion about it.
> feat: add wireguard option

- autoscaler-agents.tf
- modules/host/main.tf
This addresses the question in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/548 , and after discussion we concluded that this restart is safe and immediate.
> fix: systemctl restart k3s instead of rebooting the machine.

- kube.tf.example
Hello !
The default value of `enable_cert_manager` is `true`,
This PR fix the message in kube.tf.example saying that the default value is `false`
> Fixed kube.tf.example

- data.tf
- kube.tf.example
- locals.tf
- variables.tf
Fixes #574 
@captnCC FYI, for Calico I propose we stick to the manifest, as the helm is cumbersome and requires configuring its operator.
> Calico fix (with optional version variable)

- modules/host/locals.tf
If your local SSH environment is configured to disable authentication by public/private keys, SSH connections fail due to no other authentication means remaining.
This small modification adds `PubkeyAuthentication=yes` to the `ssh_args` variable, thus always enabling public key authentication when running Kube-Hetzner.
> Add "PubkeyAuthentication=yes" to ssh_args

- agents.tf
- autoscaler-agents.tf
- control_planes.tf
- docs/terraform.md
- locals.tf
- modules/host/locals.tf
- modules/host/main.tf
- modules/host/variables.tf
- packer.tf
- packer/hcloud-microos-snapshot.pkr.hcl
- templates/autoscaler-cloudinit.yaml.tpl
Hi, I don't know why but the last pull request has vanished..
Anyway, this know removes the initial snapshot and just uses the packer based snapshot for all created servers now, including the cluster autoscaler nodes. 
Please have a look and test it, hadn't hat much time for it yet. 
But as recently came the request, to make this work also in terraform cloud, I see the following alternatives:
1.  fall back to have the `packer` step outside of the terraform script (initial idea). Needs some additional "glue" scripting
2. avoid packer, do the snapshot with terraform - either by a separate script or include it here. Needs some additional "glue" scripting
3. Include the snapshot creation in the "host" module. Should be possible (when no `image_id`given, create first a snapshot, otherwise use …
> Microos snapshot stage 2

- kube.tf.example
- main.tf
- variables.tf
Make token usage optional to use `HCLOUD_TOKEN` environment variable instead. This helps in avoiding unintentional versioning the token within git and to use it within a pipeline.
> Hcloud token env

- kube.tf.example
Hi, the `nginx_ingress_values` variable was renamed to `nginx_values` in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/commit/adbaa4b6e7428da523c19685348de8c966827ae6. I guess it was forgotten to adjust the example at the same time. 
Have a nice weekend!
> fix: Rename `nginx_ingress_values` to `nginx_values` in example

- locals.tf
- main.tf
Updates main.tf and locals.tf file to add description attribute, which will add support for adding or making changes in the description of firewall rules, instead of empty description of rules on the Hetzner Cloud Firewalls section for the Kubernetes Cluster deployed with terraform.
> Added changes to support firewall rules' description

- README.md
- agents.tf
- kube.tf.example
- locals.tf
This modification is primarily intended to enable the implementation of the Cilium egress gateway (https://docs.cilium.io/en/v1.12/gettingstarted/egress-gateway) and allows assigning a unique floating IP to each node in the selected node pool, as well as configuring routing through the assigned floating IP.
nodepool example:
```
{
name        = "egress",
server_type = "cpx11",
location    = "fsn1",
labels = [
"node.kubernetes.io/role=egress"
],
taints = [
"node.kubernetes.io/role=egress:NoSchedule"
],
floating_ip = true # <--
count = 1
},
```
Brief summary of the changes made:
An optional floating_ip parameter has been added to the agent_nodes parameters (default value: false).
A floating IP is leased and assigned to each node in the selected node pool.
The following actions are performed …
> feat: agent_nodepools: add floating IPs option

- init.tf
- kube.tf.example
Per https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/607, any changes in the values.yaml will cause the `kustomization` null_resource block to be tainted and recreated.
I'm not sure if there are other spots where the module level variables impact the values.yaml, but am happy to add those in (if there are any)!
> Trigger recreation of kustomization when helm values change

- locals.tf
Since currently dynamic IP gathering logic from DNS is not implemented yet, updating API IP manually to a new value.
> Update Hetzner cloud API IP address

- modules/host/main.tf
This was a bug that caused the nodes not to update because of a signature verification failure on the unsigned k3s-selinux page.
For all those affected, the manual fix is in #644.
Fixes #644
> Added zypper lock to k3s-selinux

- templates/autoscaler-cloudinit.yaml.tpl
Added workaround to preserve k3s configuration files from deletion with k3s-uninstall
> added workaround to avoid empty k3s configs in screenshot

- locals.tf
- variables.tf
As discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/667 the label `node.kubernetes.io/exclude-from-external-load-balancers` must not be set at all instead of setting it to false for the control planes to be set as targets of the load-balancer.
> fix: no loadbalancer exclusion on control planes

- agents.tf
- autoscaler-agents.tf
- control_planes.tf
- init.tf
- locals.tf
- variables.tf
Fixes #682 and also brings proper k3s selinux support, before it was not activated properly, we missed it before. It needed a flag in the config, see https://docs.k3s.io/advanced#enabling-selinux-enforcement.
Because of that new rules were needed for the system upgrade controller and cluster autoscaler to be able to access, read and open certificates on the OS.
> longhorn_volume_size and selinux proper activation for k3s

- locals.tf
I deployed https://artifacthub.io/packages/helm/crowdsec/crowdsec and started to get errors in agent pods:
`Could not create watch on directory /var/log/containers : permission denied" type=file`
After reading this issue #697 and reading https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/697#issuecomment-1496607924 I created policy.
`.te` file looks like this:
```
module crowdsec_agent 1.0;
require {
type container_t;
type container_log_t;
class dir watch;
}
#============= container_t ==============
allow container_t container_log_t:dir watch;
```
Than I tested it using `.pp` file and it works OK:
```
level=info msg="Adding file /var/log/containers/traefik-6c77f68ddf-jh65p_traefik_traefik-ea4ad12fa05199b8db9d5acfbe19bc2804de8dc95fe7a03b44bd3105775e1275.log to …
```
> Adds crowdsec agent selinux config

- init.tf
`terraform apply` now updates the k3s ver without errors
I just had a question: is it possible to have a channel for cluster autoscaler as well? So we aren't fixated on a patch version but instead always pull latest?
> add k3s ver to null resource kustomization

- kube.tf.example
- locals.tf
- variables.tf
The default value of 2 may be too strict if there's many SSH keys in the ssh-agent. Some parts of this project don't support specific key selection in the ssh-agent, such as `data "remote_file" "kubeconfig"`
> Introduce ssh_max_auth_tries variable

- packer-template/hcloud-microos-snapshots.pkr.hcl
Cloud-init does not generate the connections config correctly for NetworkManager as stated in issue https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/772. By creating the necessary file, cloud-init will properly configure NetworkManager and resolve the IPv6 issue on our Nodes. IPv6 for Pods is step two.
Cloud-init correctly reads the configuration given by Hetzner, but incorrectly detects systemd-network as the network service instead of the actual NetworkManager. This is due to a missing `/etc/NetworkManager/NetworkManager.conf` file, which is required according to cloud-init's source code: https://github.com/canonical/cloud-init/blob/main/cloudinit/net/network_manager.py#L381
By creating this file before generating the network config, cloud-init is correctly guided to …
> Properly guide cloud-init to use NetworkManager

- output.tf
In my setup I also create another VMs that should use the same key as created by the module.
I also use the same network.
Using data resources and depends_on leads to recreation of resources every time a value in the kube-hetzner module changes.
> Add hcloud_network and hcloud_ssh_key ids to output so other resources outside of the module can refer to them

- kube.tf.example
- locals.tf
- modules/host/locals.tf
- modules/host/versions.tf
- packer-template/hcloud-microos-snapshots.pkr.hcl
- scripts/create.sh
- variables.tf
- versions.tf
1. Added `traefik_pod_disruption_budget` which is enabled by default
2. Added `traefik_resource_limits` which are enabled by default
3. Added `traefik_additional_ports` which allow users to add custom ports to Traefik, for example port 22 for ssh is added with these rules:
```terraform
traefik_additional_ports = [
{
name        = "ssh",
port        = 22,
exposedPort = 22
}
]
```
> A lot of QoL changes to Traefik - nothing breaking

- locals.tf
Right now, in case KlipperLB is activated scheduling on the control plane is activated too. 
This has historical reasons, please see the following quote:
> [...] initially, we only activated Klipper for single-node clusters, so we had to allow scheduling on the control plane for obvious reasons, but then I added the option of using Klipper even for multi-node clusters, and the old logic stayed.
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/201#discussioncomment-2810840
Considering the above statement it should be possible to use KlipperLB **without** enabling scheduling on the control plane at the same time.
@mysticaltech I could not find an explanation on why the code has not been changed as described in your comment. This pull request will apply the logic as …
> Allow KlipperLB to be used without scheduling on the control plane

- .github/workflows/generate-docs.yaml
Added ssh key for bypassing branch protection rules for Github Actions
This is the reference: https://stackoverflow.com/a/76135647
> Update generate-docs.yaml - Bypass branch protection

- locals.tf
It is not necessary to open the standard port 22 when using a custom port
> Drop default ssh firewall rule when custom ssh port is used

- README.md
- kube.tf.example
- locals.tf
Cilium does not pick the correct interface for the MTU calculation. In all my tests it used 1500 from the eth0 interface as base. Due to the Hetzner OpenStack VXLAN based internal networking, the "normal" 1500 MTU is reduced by 50 Bytes to 1450. Unfortunately Cilium is not able to handle it properly (https://github.com/cilium/cilium/issues/14339).
I tried Cilium with wireguard encryption and immediately saw the wrongly calculated MTU values, especially for the `cilium_wg0` interface. Inside of the tunnel everything looks fine, but outside of it you will see a lot of fragmented packets. This can be observed with tcpdump. I used this filter for the detection: `tcpdump -i eth1 -f "ip[6:2] & 0x3fff != 0x0000"`
This pull request tells Cilium which MTU to use as the base for the MTU calculation …
> Fix wrong MTU calculation for Cilium

- kustomization_user.tf
Using the `fileexists` function on the `extra-manifests` directory throws the following error when it exists: 
```
╷
│ Error: Error in function call
│ 
│   on .terraform/modules/k8s.kube-hetzner/kustomization_user.tf line 2, in locals:
│    2:   extra_manifests_exists       = fileexists("extra-manifests")
│     ├────────────────
│     │ while calling fileexists(path)
│ 
│ Call to function "fileexists" failed: "extra-manifests" is a directory, not
│ a file.
```
The function can be used only on a file, not a directory. 
A safer solution would be to use the `try` function if there is some error with `fileset`.
> Fix error with extra-manifests

- locals.tf
when using autoscaler and longhorn at the same time, the longhorn instance manager is deployed on the autoscaler nodes.
When downscaling, these pods cannot be unscheduled.
Longhorn has integrated the "kubernetesClusterAutoscalerEnabled" configuration switch into the Helmchart to solve this problem.
> fix longhorn prevent downscaling

- agents.tf
To solve https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/869 I took the implementation from https://github.com/treeumcorp/terraform-hcloud-kube-hetzner/blob/4ea2865a5a7b4a7a9a6e821b9724b4d4bffd7106/modules/host/main.tf#L122-L128 (using `nmcli` to configure the network interface in a persistent way) and added some comments. I don't know if @sshcherbinin plans to PR his changes (I also think it is useful to provide floating IP for all nodes, and put the floating IP code to the host module), but we should fix the bug in the current implementation anyway.
Tested if floating IP is persistent:
```
$ ssh -i id_ed25519 root@5.75.248.17
k3s-agent-small-zsk:~ # ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000 …
```
> [FIX] FloatingIP: Change MicroOS wickedd to networkmanager

- variables.tf
I'm trying to apply this control plane config to our cluster:
```tf
control_planes_custom_config = {
etcd-expose-metrics         = true,
kube-controller-manager-arg = "bind-address=0.0.0.0",
kube-proxy-arg              = "metrics-bind-address=0.0.0.0",
kube-scheduler-arg          = "bind-address=0.0.0.0",
kube-apiserver-arg = [
"oidc-issuer-url=https://auth.example.org/issuer",
"oidc-client-id=<redacted>",
"oidc-username-claim=name",
"oidc-username-prefix=oidc:",
"oidc-groups-claim=groups",
"oidc-groups-prefix=oidc:",
]
}
```
terraform complains with:
> Error: Invalid value for input variable
> on `kube.tf line 144`, in module "kube-hetzner":
> 
> [repeats TF file]
> 
> The given value is not suitable for `module.kube-hetzner.var.control_planes_custom_config` declared at …
> Allow for mixed-type maps for control plane config

- variables.tf
the token is used to create the hcloud secret in the kube-system namespace. Previously it could be left empty, breaking the setup during the kustomization stage. This change forces the user to set a value.
Closes: #885
> drop default for var.hcloud_token

- kube.tf.example
- locals.tf
- variables.tf
I added some advanced load balancing options and set their defaults to Hetzner's. Now the interval, timeout and retries for the health check can be customized and the load balancing algorithm is also selectable.
> Added advanced Load Balancer Options

- kube.tf.example
- locals.tf
- variables.tf
Concerning #894 
Due to k3s' defaults for `cluster-cidr` (10.42.0.0/16) and `service-cidr` (10.43.0.0/16) the creation of more than 42 nodepools and their respective subnets conflicted with these IP ranges.
Changes:
- Added a variable for setting the service-cidr
- Added cluster- and service-cidr to k3s server start arguments
- Extended documentation on theoretical maximum of nodepools
> Update handling of custom cluster-cidr

- control_planes.tf
- init.tf
- kustomization_backup.tf
- locals.tf
This fixed #913, and allows for this https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/913#issuecomment-1659589759.
> Fix first control planed depending on kustomization_backup

- variables.tf
- Unset versions of kured, as #919 was fixed upstream already. They were fast to reply to our issue, very nice of them.
- Kube and autoscaler both upgraded to default of 1.27(.x). 
_Tested and working great, so since it's really minimal, will force the merge._
> Upgraded some versions

- init.tf
Revert the last left-over from #908 so that the LB availability check is also performed when `lb_hostname` is used.
I tested it in one cluster deployment using `lb_hostname` and it seems to work fine.
> Revert to the old LB Availability Check

- locals.tf
This PR is mainly a cosmetic change to unify NetworkManager connection names to make life easier for humans interacting with `nmcli`.
Before the change:
```bash
NAME                UUID                                  TYPE      DEVICE 
cloud-init eth0     1dd9a779-d327-56e1-8454-c65e2556c12c  ethernet  eth0   
Wired connection 1  fdcd1a0a-bb69-3017-a940-96773f29fb8d  ethernet  eth1   
lo                  9e961e02-e328-4a5f-98ed-227fbf4b189d  loopback  lo 
```
After the change:
```bash
NAME  UUID                                  TYPE      DEVICE 
eth0  1dd9a779-d327-56e1-8454-c65e2556c12c  ethernet  eth0   
eth1  2a211c06-56de-35bb-967d-5b0c8378449e  ethernet  eth1   
lo    086d46a4-41f2-4089-81ce-0517216dbe80  loopback  lo  
```
> Unify NetworkManager Connection Names

- README.md
- init.tf
- kube.tf.example
- locals.tf
- templates/cilium.yaml.tpl
- variables.tf
This PR modifies the Cilium configuration to achieve the best possible performance and also native routing functionality for Cilium, allowing configuration of a fully integrated network model. For more background information, please have a look here: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/911
**Changes:**
- Fixed decoupling issue between CCM IPAM and the Cilium IPAM. Now Cilium honors the IPAM from the CCM and Hetzner Network Routes are set accordingly to allow native routing directly to pod IPs as well. See also https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/902#issuecomment-1648189450
- Updated Cilium options according to the latest deprecation warnings: https://docs.cilium.io/en/latest/operations/upgrade/#deprecated-options
- The …
> Performance Improvements and Native Routing Mode for Cilium

- README.md
Cilium 1.14 adds support to exclude specific destination CIDRs (`excludedCIDRs`) from routing to the egress gateway. Just added this to the egress gateway policy example. Cilium has exceptions by default, but only for some "known" CIDRs/IPs. Everything else matching `destinationCIDRs` would be routed to the egress gateway.
See https://github.com/cilium/cilium/pull/23448 and https://docs.cilium.io/en/stable/network/egress-gateway/#selecting-the-destination
**Ping from Pod to LB without `excludedCIDRs`:**
```bash
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
--- 10.0.0.2 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 58ms
```
**Ping from Pod to LB with `excludedCIDRs`:**
```bash
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
64 bytes from 10.0.0.2: icmp_seq=1 …
```
> Added Example to exclude Destination CIDRs from Egress Gateway

- templates/ccm.yaml.tpl
This PR fixes #934 
It seems K3s CCM is (partially) active in case Klipper LB is used. In this situation, if Hetzner CCM (HCCM) is running on a CP node, there will be a port conflict as both K3s CCM and HCCM try to bind to port `10260`. This is caused by a new feature introduced in Kubernetes 1.27 with https://github.com/kubernetes/kubernetes/pull/108838.
Thanks to [@apricote](https://github.com/apricote) we have a workaround to disable the HCCM webhook listener by adding `--webhook-secure-port=0` flag to HCCM. This can be used in HCCM > v1.16.0.
See also https://github.com/kubernetes/kubernetes/issues/120043.
I tested this flag with and without using Klipper LB and it seems to work fine :slightly_smiling_face:
> Fix CCM Webhook Listener Port Collision

- output.tf
Hi there,
I'm currently building a terraform environment to add root-server to this cluster.
This is my current state of work: https://github.com/nupplaphil/terraform-root-kube-hetzner
Since I don't want to mix up root server and hcloud server, I choose a different repo for it.
The only thing missing is the "glue" between the hcloud terraform module and my root terraform module.
--> the k3s token and endpoint is missing.
With these two outputs, I was successfully to add a root-server to a cluster out of this project :)
btw the cilium config
```yaml
loadBalancer:
acceleration: native
```
doesn't work because XDP is incompatible with the vlan interface of the vSwitch subnet.
--> I manually overwrite the `cilium_values`
> Add k3s-token and k3s-endpoint as output so other modules can re-use it.

- modules/host/main.tf
You should wait for the cloudinit's work to be completed  to avoid collisions, locks and other things.
> waiting for the completion of the cloudinit's work

- README.md
- locals.tf
- modules/host/main.tf
- variables.tf
After two intensive weeks with all kinds of trial and errors with cluster restoration from etcd backup, actually only this postinstall_exec hook is needed to make it work.
> adding postinstall_exec to hook restore commands

- README.md
- docs/terraform.md
- kube.tf.example
- variables.tf
DNS 9.9.9.9 applies filtering based on the VirusTotal database. My domain was included in this database by mistake and I spent several days debugging to understand what was wrong.
After updating the cluster and the release of the 9.9.9.9 resolver, my sites in the yucca.app domain began to sometimes return http 500, this is because nginx ingress cannot resolve the request on the incoming domain.
I suggest not using the default DNS which uses any filtering and can lead to service failure. The use of such resolvers should be a conscious choice. On its website, quad9 suggests using the address without filtering, so I replaced it in the default variable.
> Change default DNS servers

- locals.tf
- variables.tf
Example for Cloudflare:
```terraform
traefik_additional_trusted_ips = [
"173.245.48.0/20",
"103.21.244.0/22",
"103.22.200.0/22",
"103.31.4.0/22",
"141.101.64.0/18",
"108.162.192.0/18",
"190.93.240.0/20",
"188.114.96.0/20",
"197.234.240.0/22",
"198.41.128.0/17",
"162.158.0.0/15",
"104.16.0.0/13",
"104.24.0.0/14",
"172.64.0.0/13",
"131.0.72.0/22",
"2400:cb00::/32",
"2606:4700::/32",
"2803:f800::/32",
"2405:b500::/32",
"2405:8100::/32",
"2a06:98c0::/29",
"2c0f:f248::/32"
]
```
> Traefik Trusted IPs

- variables.tf
As discussed here: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/539
I think it makes sense to do a check on uniqueness of names.
> Add validation for uniqueness of nodepool-names

- agents.tf
- control_planes.tf
- docs/terraform.md
- locals.tf
Applied the same changes for the agent nodes
Sorry for the delay ;]
Also updated the update script so it checks if the file to backup exists first.
This prevents on cluster init that you get a `cp` error (does not impact the cluster)
> feat: dynamic k3s configuration for agents

- docs/terraform.md
- init.tf
- kube.tf.example
- locals.tf
- templates/nginx_ingress.yaml.tpl
- templates/traefik_ingress.yaml.tpl
- variables.tf
`providers.kubernetesingress.ingressendpoint.publishedservice` is now set by default and will also work with custom namespace targets :)
It is also now possible to deploy nginx or traefik to a namespace of your liking.
I did not change the nginx one to the default `ingress-nginx` since I don't know if changing the targetNamespace causes orphaned HelmReleases ;]
This should close
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1048
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1042
> Publish traefik service by default, and allow custom namespace target for the ingress_controllers

- agents.tf
- control_planes.tf
- docs/terraform.md
- kube.tf.example
- locals.tf
- variables.tf
This is especially handy when you want to set different reserved compute resources based on nodepool specs
> feat: kubelet args per nodepool

- autoscaler-agents.tf
- kube.tf.example
- templates/autoscaler.yaml.tpl
- variables.tf
I found that the autoscaler support for taints and labels was very very lacking! The autoscaler predicate didn't know before hand the taints and labels of the nodepools . And there was no support of taints/labels per nodepool. 
This also makes it so that multi arch node pools are possible! I have been running this a month or so~ and no quirks :dancers: 
This PR goes hand in hand with a PR in autoscaler. eg breaking-change
https://github.com/kubernetes/autoscaler/pull/6184
> feat: taints and labels per autoscaler nodepool

- control_planes.tf
- init.tf
@mysticaltech @Silvest89 This basically fixes all the issues I experienced in #1073 .
I 100% sure, that all other problems I had in #1073 were basically only happening because of pure randomness. Due these changes updating k3s configs only happens when first node is provisioned with base config and has running k3s.service. Also made sure that kustomization regarding all the other stuff CNI/CSI... is happening after all control nodes are deployed and have running k3s.
> Fix missing dependencies for #1073

- kube.tf.example
As it stood, it looked like the `firewall_kube_api_source` setting would also apply firewall rules to the load balancer when the `use_control_plane_lb` setting was set to true. 
Adding additional documentation to the kube.tf.example file, so that it is clear that firewall rules cannot be applied to load balancers just yet. Hopefully this addition prevents users from having their API exposed to the world whilest they might think it is not.
> added additional documentation for the firewall_kube_api_source setting

- .github/workflows/lint_pr.yaml
- docs/terraform.md
- versions.tf
> Fixing github module issue

- README.md
Remove namespace from syntax, which is not needed when editing node labels. Fix '_' to '-' and clarify text.
> chore(docs): k3s_upgrade label

- kube.tf.example
- locals.tf
- variables.tf
Useful if someone wants the new v3 opentelemetry metrics and tracing.
> feat: added option to pin traefik image tag with example for traefik beta

- init.tf
- kube.tf.example
- locals.tf
- templates/nginx_ingress.yaml.tpl
- templates/traefik_ingress.yaml.tpl
- variables.tf
With these two new options, you can control the helm chart version for traefik and nginx ingresses.
> feat: specify the version of the ingress (traefik & nginx) helm chart

- locals.tf
- packer-template/hcloud-microos-snapshots.pkr.hcl
> Fix selinux issues with k3s binary

- locals.tf
Found some issues with the SELinux policy when trying to chain the [Linkerd CNI plugin](https://linkerd.io/2.14/features/cni/) with Cilium. Determined additional required policy statements by running `grep "denied" /var/log/audit/audit.log | audit2allow -M linkerd` until no more denied errors logged. Patched in the additional statements to existing SELinux module.
For reference, generated module was:
```module linkerd 1.0;
require {
type etc_t;
type container_t;
class file { create setattr unlink write };
class dir watch;
}
#============= container_t ==============
#!!!! This avc is allowed in the current policy
allow container_t etc_t:dir watch;
#!!!! This avc is allowed in the current policy
allow container_t etc_t:file { create setattr unlink write };```
> Update SELinux policy to support linkerd-cni

- locals.tf
I noticed that the Traefik configuration includes the option `--entrypoints.tcp=true`,
which generates an entry point named `tcp` without configuring it.
While this option doesn’t cause any harm, it is entirely unnecessary.
Therefore, I suggest removing it.
> chore(traefik): remove unused entrypoint

- locals.tf
Fixes:
,----
| Found cloud-config data types: user-data, vendor-data |
| 1. user-data at /var/lib/cloud/instances/41307264/cloud-config.txt:
|   Invalid cloud-config /var/lib/cloud/instances/41307264/cloud-config.txt
|   Error: Cloud config schema errors: runcmd.1: ['semanage', 'port',
|     '-a', '-t', 'ssh_port_t', '-p', 'tcp', 60022] is not of type 'string',
|     runcmd.1: ['semanage', 'port', '-a', '-t', 'ssh_port_t', '-p', 'tcp',
|     60022] is not valid under any of the given schemas
`----
> locals: quote var.ssh_port to provided a valid cloud-init user-data

- kube.tf.example
- locals.tf
Added comments in kube.tf.example to document the possible use of lock expiration (lock-ttl).
Addresses https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1182 .
> fix: removed the default kured lock expiration as it is dangerous.

- README.md
I went around in circles a little trying to work out why I couldn't get some new Terraform features to deploy. Turns out I had installed Terraform with Brew from a community maintained version, which is quite out of date. 
Terraform recommend using their signed maintained installation instead: https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
> Update Brew Terraform installation instructions

- README.md
- locals.tf
This PR contains a Kured configuration fix and README improvements and fixes regarding automatic and manual updating.
- The sentinel path of Kured needs to be adjusted to point to the mountpoint in the container and not the original host path
- Don't start `transactional-update` directly from the console, instead trigger the systemd service
- Clarify control of automatic k3s updating
Fixes #1204.
> Automatic updating fixes (README and Kured options)

- agents.tf
- init.tf
- locals.tf
- variables.tf
New variable : `agent_nodes_custom_config`. Works exactly like `control_planes_custom_config`.
> feat: allow custom configuration for agent nodes

- templates/autoscaler.yaml.tpl
Enable monitoring for cluster autoscaler by opening pod port 8085
More infos: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-monitor-cluster-autoscaler
> open autoscaler pod port to enable monitoring via port 8085

- README.md
- control_planes.tf
- init.tf
- kube.tf.example
- locals.tf
- variables.tf
This PR introduces Cilium 1.15.1, which supports Kubernetes versions 1.26, 1.27, 1.28, and 1.29.
This will also fix #1210 (#1199). Before this change, Cilium could only run in hybrid kube-proxy replacement mode. Now, full replacement is possible with the newly introduced `disable_kube_proxy` flag.
Another improvement is the bypassing of iptables connection tracking for Pod traffic in Cilium. This is only effective in native routing mode (`cilium_routing_mode = "native"`).
> For the case when eBPF Host-Routing cannot be used and thus network packets still need to traverse the regular network stack in the host namespace, iptables can add a significant cost. This traversal cost can be minimized by disabling the connection tracking requirement for all Pod traffic, thus bypassing the iptables …
> Introducing Cilium 1.15.1 and Full kube-proxy Replacement

- kube.tf.example
- templates/autoscaler.yaml.tpl
- variables.tf
Made possible by #1231 and a fix to the autoscaler by @Silvest89  🚀
> Support for v1.29

- README.md
- kube.tf.example
Small tweaks in the text for added clarity.
> kube.tf.example tweak

- locals.tf
See issue https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1252
Kustomize currently failes to install, system-upgrade-controller has not enough permission to access kube-system namespace. This is caused by system-upgrade-controller.yaml fetched from master branch of rancher repo.
This pull requests uses the last working commit of this file.
BTW: Would love to become a official contributor to this project
> Use a specific commit of system-upgrade-controller.yaml 

- locals.tf
Closes #1271 
- permission map is not defined for class anon_inode 
- permission read is not defined for class anon_inode 
- permission write is not defined for class anon_inode
> Remove unknown permissions from anon_inode

- README.md
I managed to make kube-hetzner work on Terraform Cloud. Since the ssh_private_key and ssh_public_key variables expect the file contents rather than the path to the files (as was the case in the past), the existing instructions are more convoluted then they need to be (provided users are ok with nog password protecting their ssh private key). I assume Terraform Cloud encrypts their sensitive variables in a different way already.
> Add instructions on running from Terraform Cloud

- modules/host/main.tf
There are situations where the ssh key contains carriage return chars, for example when generating the key using 1password.
The change ensures that the carriage return character (`\r`) is removed from the ssh_client_identity variable using sed. This will prevent authentication issues during `terraform apply`.
> Strip carriage return from ssh_client_identity

- templates/ccm.yaml.tpl
When a new service of type LoadBalancer is requested k3s will use besides the public IPv4 & 6 of the Hetzner LB also the private ip of that LB which is wrong. 
This also fixes the external-dns updating A records with the private IP of the LB
With `HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS: true` ( this is the default value ) 
external-dns will detect external load balancer IP's and will create following A records: ( cloudflare, but with other dns providers will be the same issue )
With this new change:
With `HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS: false`
With this new change external dns won't create the A record for the private iP
> Fix LoadBalancer service using both public and private IP of LB's 

- autoscaler-agents.tf
- kube.tf.example
- templates/autoscaler.yaml.tpl
- variables.tf
This PR fixes https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1278 by exposing a variable to increase server creation timeout of `cluster-autoscaler`.
> autoscaler: Add support to set HCLOUD_SERVER_CREATION_TIMEOUT 

- autoscaler-agents.tf
- kube.tf.example
- variables.tf
This PR allows to set `kubelet` arguments (through `kubelet_args`) for each autoscaler pool individually or globally (`k3s_autoscaler_kubelet_args`).
Fixes https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1281
> autoscaler: allow to set kubelet-arg for autoscaler nodes

- examples/kustomization_user_deploy/README.md
Fix typo in the `resources` configuration field and improve readability using numbered lists.
> docs: fix typo and improve readability of `examples/kustomization_user_deploy/README.md`

- kube.tf.example
Add resource delete protection variables to kube.tf.example.
Added via https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1300 but without the `kube.tf` example.
> Add resource delete protection variables to kube.tf.example

- agents.tf
> pass zram to agents as well

- locals.tf
Fixes #1335 and #1322. Notice that this depends on the Traefik version so this might not be a real fix if someone specifies a traefik version that comes before https://github.com/traefik/traefik-helm-chart/commit/7e349d4782b72c36220a1ec8dace803640e289e0
> Fix configuration when exposing additional ports

- init.tf
- kube.tf.example
- templates/plans.yaml.tpl
- variables.tf
on small clusters eviction of pods during system-upgrade of k3s might hang since pods cannot be scheduled on a different node during upgrade.
see the example plans of [system-upgrade-controller](https://github.com/rancher/system-upgrade-controller?tab=readme-ov-file#example-plans) as well
> adds system_upgrade_enable_eviction flag

- locals.tf
See @maggie44's comment here: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/697#issuecomment-2125667175
> Adding missing permissions for prometheus node exporter

- README.md
- kube.tf.example
- packer-template/hcloud-microos-snapshots.pkr.hcl
Hetzner announced their new Intel cloud servers yesterday, CX22-CX52. They are much better value for money than the old Intel and even current AMD types while being almost exactly the same price. This PR updates the default templates to use CX22 and CX32 instances where CPX11 and CPX21 were used. This both reduces the cost and increases the performance of the default configuration.
https://www.hetzner.com/news/new-cx-plans/
This has been tested by following through the tutorial and creating a new cluster from scratch. CX22 is used to create the x86 snapshot, and also as the default type in the generated `kube.tf`.
Hetzner will discontinue the old Intel server types in 6 months.
> Update Default Server Types to reflect new pricing and server types

- locals.tf
#1362 
added default value for kured_options.lock-ttl= 30m
> 30m lock-ttl default added for kured_options

- init.tf
- locals.tf
- templates/hcloud-csi.yaml.tpl
- variables.tf
fixes #1416 
I am not sure whether this works, because I just realised I never used the hetzner csi. 
but I think it should
builds upon #1415
> Helmchart hetzner csi

- locals.tf
Reverts kube-hetzner/terraform-hcloud-kube-hetzner#1420 because ttl on the lock can have cascading effects in some instances and take the whole cluster down.
> Revert "30m lock-ttl default added for kured_options"

- init.tf
- kube.tf.example
- locals.tf
- templates/plans.yaml.tpl
- variables.tf
Sometimes a cluster operator might prefer to specify the k3s version (e.g. `v1.29.6+k3s2`) instead of the channel (e.g. `v1.29`, `stable` etc.)
Reasons for that could be not wanting the system upgrade controller to run at unpredictable times, or having more fine-grained control over the running version.
This PR introduces a new variable `install_k3s_version` in `kube.tf`. If undefined, the present behavior is preserved such that current installations are not affected. However, when defined, this variable takes precedence over `initial_k3s_channel`.
The mechanism for upgrades in either case continues to be the system upgrade controller.
> Allows specifying k3s version

- kube.tf.example
- modules/host/templates/cloudinit.yaml.tpl
wrap swap creation with transactional-update --continue shell to fix the issue of missing swap after node reboot fix for https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1399
I see the proper transaction with 4Gb used for swap
```
───┼────────┼───────┼──────────────────────────┼──────┼────────────┼─────────┼───────────────────────┼─────────
0  │ single │       │                          │ root │            │         │ current               │
1  │ single │       │ Sat Jun 29 19:42:50 2024 │ root │  80.40 MiB │         │ first root filesystem │
2  │ single │       │ Tue Jul  2 06:03:26 2024 │ root │  14.76 MiB │ number  │ Snapshot Update of #1 │
3- │ single │       │ Tue Jul  2 06:04:01 2024 │ root │ 352.00 KiB │ number  │ Snapshot Update of #2 │
4+ │ single │       │ …
```
> Fix swap creation issue

- init.tf
- kube.tf.example
- templates/plans.yaml.tpl
- variables.tf
This PR adds a new variable `system_upgrade_use_drain` (default `true`), which represents the current default behaviour to advise system-upgrade-controller to drain nodes before performing a k3s upgrade.
When set to `false` the agent plan will be configured to cordon nodes during upgrades, which prevents that new pods are scheduled but keeps all existing pods running on that node.
This may be useful if you have pods which are known to start slowly, e.g. because they have to mount volumes with many files which require to get the right security context applied.
Nothing has changed for the server plan, which uses cordon anyway.
> Add option to use "cordon" instead of "drain" for k3s upgrades

- docs/terraform.md
- init.tf
- locals.tf
Using `hetzner_csi_values` didn't actually do anything. Now it does.
> Fix regeneration and rendering of hetzner_csi_values

- templates/ccm.yaml.tpl
Closes #1477
Fix the issue described by overriding `args` instead of `command`. In addition, I also added an argument (`--route-reconciliation-period=30s`) that was added in HCCM v1.14.2.
> fix(hccm): custom args are ignored

- docs/terraform.md
- output.tf
This change adds new outputs `control_plane_nodes` and `agent_nodes` to output a list of objects forwarding all outputs from modules/host (ipv4_address, ipv6_address, private_ipv4_address, name and id).
Closes #1460
---
main.tf:
```terraform
module "prod-us-east-1" {
source = "../terraform-hcloud-kube-hetzner"
control_plane_nodepools = [
{
name        = "control-plane",
server_type = "cpx21",
location    = "ash",
count       = 3
labels      = []
taints      = []
}
]
agent_nodepools = [
{
name        = "worker",
server_type = "cpx21",
location    = "ash",
count       = 3
labels      = []
taints      = []
}
]
}
output "nodes" {
value = concat(module.prod-us-east-1.agent_nodes, module.prod-us-east-1.control_plane_nodes)
}
```
output:
```
module.prod-us-east-1.null_resource.kustomization: …
```
> add control_plane_nodes and agent_nodes output

- kube.tf.example
There was an error in the documentatio about the example file.
Resulting in error when using autoscaler:
Error: Invalid expression                                                                                                                                                │                                                                                                                                                                         
│   on kube.tf line 333, in module "kube-hetzner":                                                                                                                        
│  333:       taints      =                                                                                                                                               
│  334: …
> autoscaler formatting documentation fix

- kube.tf.example
- variables.tf
Otherwise many installations will never be updated and fall behind the stable branch. Besides, setting a dynamic value here requires less manual version updates in the future.
> feat: use stable k3s branch

- locals.tf
Should this be updated automatically in the future by dependabot/renovate?
> chore: bump system-upgrade-controller version to 0.14.2

- control_planes.tf
- kube.tf.example
- locals.tf
- variables.tf
Structured authentication configuration allows Kubernetes to support multiple identity providers. To use this feature you'll need version 1.30 of Kubernetes at-least.  
Details:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#using-authentication-configuration
Example how to use github actions pipeline token to access cluster 
```yaml
name: 'test kubectl'
on:
workflow_dispatch:
workflow_call:
permissions:
id-token: write
contents: read
jobs:
restart-services:
name: 'Test kubectl'
runs-on: ubuntu-latest
environment: development
steps:
- name: Install OIDC Client from Core Package
run: npm install @actions/core@1.10.1 @actions/http-client
- name: Get Id Token
uses: actions/github-script@v6
id: idtoken
with:
script: |
const coredemo = require('@actions/core')
// On …
```
> Add support for structured auhentication configuration.

- README.md
The Brew form for Packer mentioned in the readme is [disabled](https://formulae.brew.sh/formula/packer). 
According to Hashicorp's documentation, the new form is **[hashicorp/tap/packer](https://developer.hashicorp.com/packer/tutorials/docker-get-started/get-started-install-cli)**.
Error message:
```bash
brew install packer
Error: packer has been disabled because it will change its license to BUSL on the next release! It was disabled on 2024-09-27.
```
> Docs: Replace disabled brew formular for packer

- output.tf
For testing purposes I started the implementation of my cluster setup with a single-node cluster and added Hetzner DNS Api to update a domain to the cluster ingress ip. However for the single node setup, the IPv6 was not set, because the conditions were not met.
This PR fixes setting the IPv6 Addresses in the module output for single-node clusters (that do not have an external loadbalancer).
> Fix: Output public ipv6 on single-node-clusters

- kube.tf.example
- variables.tf
#1512 introduced a new var `sys_upgrade_controller_version`.
- Corrected the description, which was an incorrect copy-paste from another var.
- Added the var to kube.tf.example
#1506 reverted cluster-autoscaler back to the community version. However, the default version for var `cluster_autoscaler_version` (1.31.1), does not correspond to the new default `initial_k3s_channel` ("stable", which is currently still 1.30) and the doc says these versions *should* correspond. So I put version 1.30.3 as default. This is in line with the initial_k3s_channel and includes the patch for the Hetzner deprecation of CX11.
Added `csi_driver_smb_version` to kube.tf.example
> Update doc, default values and kube.tf with recent changes to cluster_autoscaler_version, initial_k3s_channel and var sys_upgrade_controller_version

- agents.tf
- kube.tf.example
The maximum size for volumes is 10,240 GB
https://docs.hetzner.cloud/#volumes-create-a-volume
> Updated maximum volume size to 10240

- kube.tf.example
- locals.tf
- variables.tf
See https://artifacthub.io/packages/helm/cert-manager/cert-manager/#installcrds-~-bool.
The new crds.enabled and keep were introduced in v1.15: https://github.com/cert-manager/cert-manager/releases/tag/v1.15.0
> Replace deprecated cert-manager value "installCRDs" by "crds.enabled" and "crds.keep"

- locals.tf
This is needed for example for DaemonSets that require hostPath volume mount.
> SELinux: allow RW access in /var/lib

- README.md
- kube.tf.example
- packer-template/hcloud-microos-snapshots.pkr.hcl
- Added detailed instructions in README.md for using the 'udica' tool to create custom SELinux policies, promoting better security practices.
- Updated kube.tf.example to include a note on SELinux enforcement and the use of 'udica' for targeted policies.
- Included 'udica' in the list of needed packages in packer-template/hcloud-microos-snapshots.pkr.hcl to ensure availability during image creation.
Part of #697 
Thanks for the hint @carolosf.
> Add Udica for easy SELinux

- packer-template/hcloud-microos-snapshots.pkr.hcl
This tiny PR installs qemu-guest-agent, to allow the password reset to work in hetzner GUI.
It may be useful in case of emergency (ssh key lost, using console in hetzner, ...)
> Feat(packer): Install qemu-guest-agent

- init.tf
I explicitly pin certain versions. When I changed `var.longhorn_version` from `v1.8.0` to `v1.8.1`, I noticed that the new version was not deployed.
`var.longhorn_version` and other version variables are not part of the deployment triggers.
Add any missing version variables to the list of deployment triggers.
> Add missing version variables to kustomization triggers

- README.md
- kustomization_user.tf
- variables.tf
If you'd like to use a different folder name, you can configure it using the extra_kustomize_folder variable. By default, it is set to extra-manifests. This can be useful when working with multiple environments, allowing you to deploy different manifests for each one.
> Make Kustomization folder configurable

- placement_groups.tf
This PR is suppposed to fix placement-group creation for agent node-pools.
I was struggling to get a cluster up and running with the following node-pools, because there was only 1 placement-group created for my total of 13 agents.
```terraform
control_plane_nodepools = [
{
name        = "control-plane-small-1-${var.location}",
server_type = "cpx11",
location    = var.location,
labels      = [],
taints      = [],
count       = 3
}
]
agent_nodepools = [
{
name        = "agent-medium-1-${var.location}",
server_type = "cpx31",
location    = var.location,
labels      = [],
taints      = [],
count       = 10
},
{
name        = "agent-large-1-${var.location}",
server_type = "cpx41",
location    = var.location,
labels      = [],
taints      = [],
count       = 3
}
]
```
> fix(): placement-groups for agents

- locals.tf
The change enables encryption for pure node to node traffic when WireGuard is in Cilium.
> feat: enable nodeEncryption in cilium_values when wireguard is enabled

- modules/host/main.tf
One-line fix for bug which only appears if you use only private ips.
> fix: host module should not create rdns if instances have only private ips.

- modules/host/main.tf
The servers are dual-stack (each server has an IPv4 address and an IPv6 address).
If there is an IPv4 address, a reverse DNS record for IPv4 is created as expected.
If there is also an IPv6 address, the corresponding resource record for the IPv6 address is missing.
Create reverse DNS records for all enabled IP protocols.
> Create IPv6 reverse DNS records for dual-stack servers

- modules/host/templates/cloudinit.yaml.tpl
Fixes issue that resulted in cloud-init not running:
>  Error: Cloud config schema errors: debug: Additional properties are not allowed ('debug' was unexpected)
> cloud-init: Remove invalid "debug" key

- autoscaler-agents.tf
k3s' config.yaml for control planes and for agent pool nodes contains an `selinux` key whose value depends on `var.disable_selinux`. However, nodes created by the autoscaler always had `selinux=true` in their config, even though selinux is correctly disabled for them in their cloud init.
This PR applies the value of `var.disable_selinux` to the k3s' config.yaml for autoscaler nodes as well.
> fix: Respect var disable_selinux on autoscale nodes

- templates/autoscaler.yaml.tpl
fix #1694
ref: https://github.com/kubernetes/autoscaler/pull/7904
> Fix missing `volumeattachments` permission for autoscaler clusterrole

- init.tf
For small but HA clusters (i.e., 3 control plane nodes with `allow_scheduling_on_control_plane=true`) it was not possible to create external load balancer.
1. The first patch fixes an issue where the external load balancer couldn't be created because of wrong subnet association. Previously it tried to take a subnet from the first agent node, but as in this configuration there are no agents, there was an error during LB declaration.
2. Second issue was with the LB node association due to wrong label selector. Previously control plane nodes were omitted from external load balancer label selector as the "role" tag was overwritten by agent node. It resulted in the following label selector:
`cluster=...,engine=k3s,provisioner=terraform,role=agent_node`
The patch fixes the selector to include …
> Fix external load balancer configuration for agent-less clusters

- locals.tf
This ensures automatic pod restart with a new configuration in case of changed values, which makes the deployment easier to manage.
Noted as the way to go when modifying configuration with Helm (https://docs.cilium.io/en/stable/configuration/index.html#making-changes).
> Enable gradual roll-out on Cilium config update

- docs/terraform.md
- modules/host/out.tf
- output.tf
It allows for easy integration with DNS terraform module to dynamically create DNS records based on the current cluster configuration.
It will be extended with IPv6 once #1704 gets addressed and #1739 gets merged.
> Add output with domain associations to IPs

- init.tf
This pull request resolves issue #1677 by fixing the YAML formatting for Helm chart `valuesContent`.
**The Problem:**
The use of `trimspace()` before `indent()` in `init.tf` was causing malformed YAML in the generated HelmChart resources. This resulted in unreadable `valuesContent` when inspected with `kubectl`, showing broken indentation and unnecessary escape characters.
**The Fix:**
This PR removes the `trimspace()` function from the `values` argument for all Helm chart configurations within the `null_resource.kustomization` resource. The `indent()` function is retained to ensure proper indentation within the template.
**Impact:**
- Fixes YAML formatting for new cluster provisions.
- Non-disruptive for existing clusters, as the provisioner will not re-run unless its triggers change.
> Fix(helm): Correct YAML formatting for Helm chart values

- variables.tf
This change relaxes the type constraint on the 'extra_kustomize_parameters' variable from map(any) to any. This allows passing a map with mixed value types, such as strings and objects, which is a common use case for kustomize parameters. This change is fully backward compatible. Fixes #1679
> fix: Allow any type for extra_kustomize_parameters

- autoscaler-agents.tf
- locals.tf
- variables.tf
- versions.tf
Previously the DNS servers were set in the cloud-init only, which worked for the initial server bootstrap, but later these DNS servers get replaced by NetworkManager.
This patch fixes this behaviour by saving the custom DNS servers in NetworkManager which has the added benefit of enabling user to change it after deployment.
> Fix custom DNS servers

- locals.tf
This PR fixes issue #1707.
The previous logic in `locals.tf` incorrectly added a default firewall rule for SSH even when `firewall_ssh_source` was explicitly set to `null`. This exposed the SSH port unintentionally.
This change removes the redundant and incorrect block, ensuring that setting `firewall_ssh_source = null` correctly disables the SSH firewall rule, as was the original intention. The default behavior of allowing SSH from all sources when the variable is not set remains unchanged.
> Fix: SSH firewall rule not disabled when set to null

- agents.tf
- autoscaler-agents.tf
- control_planes.tf
This commit resolves an issue where user-provided Kubelet arguments were being overridden by nodepool defaults. The concatenation order in control_planes.tf, agents.tf, and autoscaler-agents.tf has been corrected to ensure that user-defined configurations are applied with the correct precedence. Fixes #1709
> fix: Correct Kubelet argument precedence

- locals.tf
This PR fixes the issue reported in #1721.
In single-node clusters, or any cluster using klipper-lb instead of a Hetzner Load Balancer, the Traefik `web` entrypoint configuration was being generated as an empty block if HTTPS redirection was disabled. This caused Traefik to fail to listen on port 80.
This fix makes the generation of the `web` entrypoint conditional. It will now only be created if HTTPS redirection is enabled OR if the cluster is not using klipper-lb. This ensures a valid configuration in all scenarios and is fully backward-compatible.
> fix(traefik): Correctly handle web entrypoint for single-node clusters

- variables.tf
This PR changes the default `address_for_connectivity_test` from `1.1.1.1` to `8.8.8.8` to resolve timeout issues in the `nbg1` location.
Users were experiencing `remote-exec provisioner error` with exit code 124 when provisioning servers in the `nbg1` location. The error occurs during the connectivity test that pings `1.1.1.1` before downloading k3s.
- Changed the default value of `address_for_connectivity_test` from `1.1.1.1` (Cloudflare DNS) to `8.8.8.8` (Google DNS)
- This should provide better connectivity reliability in the `nbg1` datacenter
This change maintains backward compatibility as users can still override the variable if needed.
Fixes #1762
> fix: change default connectivity test address to 8.8.8.8

- kubeconfig.tf
With an ipv6-only node, I received this error after trying to apply a change which needed to destroy a node in the cluster.
```
│ Error: unable to open remote client: couldn't establish a connection to the remote server 'root@<redacted_ip>:1:22': dial tcp: address <redacted_ip>:1:22: too many colons in address
│ 
│   with module.kube-hetzner.data.remote_file.kubeconfig,
│   on .terraform/modules/kube-hetzner/kubeconfig.tf line 1, in data "remote_file" "kubeconfig":
│    1: data "remote_file" "kubeconfig" {
```
> fix too many colons error due to ipv6

- autoscaler-agents.tf
- kube.tf.example
- variables.tf
`var.agent_nodes_custom_config` is applied to the k3s config.yaml for nodes created for the `agent_nodepools`. However, it was not applied to nodes created by the autoscaler. So it was impossible to configure autoscaler nodes to expose their kube-proxy metrics.
This PR applies `var.agent_nodes_custom_config` to nodes created by the autoscaler as well. I think we don't need a separate variable for that: worker nodes are worker nodes, whether they are created by static `agent_nodepools` or dynamically at runtime by `autoscaler_nodepools`.
I added `agent_nodepools` to `kube.tf.example` as well and slightly improved the doc.
> Fix: Apply var.agent_nodes_custom_config to autoscale nodes

- locals.tf
According to example in official Hetzner repo it's a good approach to follow, WDYT?
https://github.com/hetznercloud/csi-driver/blob/018e2478d98b8f81a79f3d1a2c846decb8e4de6a/chart/example-prod.values.yaml#L81
P.S.
Tried to follow contribution guide, but did not find `staging` branch
> 7. Open a Pull Request targeting the staging branch.
> Do not schedule CSI pods on control-plane by default

- docs/llms.md
This PR introduces an intricate guide for configuring the kube-hetzner Terraform module for k3s on Hetzner Cloud, specifically tailored for LLM workloads.
> feat: Add Intricate Guide for LLMs

- examples/micro_os_rollback/Readme.md
This weekend I  run into the problem that after automated OS upgrade and reboot Nginx failed to start again most likely because of https://github.com/kubernetes/kubernetes/issues/130999
So I needed to roll back the node's OS and did not find anything here :(
Here is how it did it, I think this might be useful to others too.
> docs: Add manual rollback instructions for MicroOS nodes

- locals.tf
Should fix #1790 and I don't see any side effects, but please bear in mind that I only tested this in single cluster mode.
> fix: https port in single node cluster (closes #1790)

- .gitignore
- kubeconfig.tf
- Fixes the kubeconfig generation error when using private-only deployments
- Changes the reference from deprecated `network_ip` to the correct `hcloud_load_balancer_network` IP
- Ensures backward compatibility by only affecting the private IP configuration path
Fixes #1809
> fix: use load balancer network IP for private-only deployments

- locals.tf
The current logic does not work for all OS and addresses the issue when testing [LeapMicro support](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1628#issuecomment-3038598265).
Tested with
> chore: robostify default interface detection

- locals.tf
- Fixes #1798 where nmcli commands would hang during cloud-init if NetworkManager wasn't ready yet
- This caused cloud-final.service to timeout and prevented k3s-agent from starting on new autoscaled nodes
- Adds a 60-second wait loop for NetworkManager to be active before attempting DNS configuration
The issue occurred because:
1. cloud-final.service runs the DNS configuration script
2. The nmcli commands hang if NetworkManager isn't ready yet (can take ~50 seconds on some nodes)
3. This causes cloud-final.service to timeout
4. The timeout kills the entire k3s-agent installation process
The fix:
- Waits up to 60 seconds for NetworkManager to be active using `systemctl is-active`
- If NetworkManager doesn't start within the timeout, exits gracefully (exit 0) without failing cloud-init
- …
> fix: wait for NetworkManager before setting DNS to prevent race condition

- locals.tf
- Fixes cert-manager helm chart installation failure due to incorrect extraArgs format
- Changes from object format to array format as expected by the chart's values schema
The cert-manager helm chart was failing to install with the error:
```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
cert-manager:
- extraArgs: Invalid type. Expected: array, given: object
```
This was happening because we were providing extraArgs as a key-value object instead of an array of strings.
Changed the extraArgs format in `locals.tf` from:
```yaml
extraArgs:
--feature-gates: ACMEHTTP01IngressPathTypeExact=false
```
To the correct array format:
```yaml
extraArgs:
- --feature-gates=ACMEHTTP01IngressPathTypeExact=false
```
This is a corrective fix …
> fix: correct cert-manager extraArgs format to use array syntax

- README.md
- docs/add-robot-server.md
- init.tf
- kube.tf.example
- locals.tf
- values-export.tf
- variables.tf
After HCCM is now integrated via helm, there's only the ability missing to configure its values.
I've extracted the instructions from https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1311#discussioncomment-11160315, which I am using since its existence.
As this config conflicts with my custom HCCM install right now, I haven't tested it yet - maybe somebody else will? ;)
close #1405 #1311 #283
> feat: add support & docs for adding Hetzner Robot servers as nodes

- docs/add-robot-server.md
- kube.tf.example
- locals.tf
- templates/hcloud-ccm-helm.yaml.tpl
This PR fixes critical issues introduced in #1792 that prevented the Hetzner CCM helm values customization from working properly, which is essential for Robot server integration.
1. **Template not using values parameter**: The `hcloud-ccm-helm.yaml.tpl` had hardcoded values instead of using the `${values}` parameter
2. **Missing default values**: Default CCM values were in the template instead of `locals.tf`
3. **Missing documentation**: Added proper example in `kube.tf.example`
4. **Documentation improvements**: Enhanced Robot server guide with OS recommendations and MTU warnings
- ✅ Fixed `hcloud-ccm-helm.yaml.tpl` to use `${values}` parameter (aligns with other helm charts)
- ✅ Moved default CCM values from template to `locals.tf` 
- ✅ Added `hetzner_ccm_values` example to …
> fix: correct Hetzner CCM helm integration for Robot server support

- locals.tf
Currently, NetworkManager generates /etc/resolv.conf based on the provided dns_servers list. However, when the connection method is set to auto (the default), Hetzner’s default nameservers are also appended.
For example, with the following configuration:
```yaml
dns_servers = [
"1.1.1.1",
"8.8.8.8",
"2606:4700:4700::1111",
]
```
The resulting /etc/resolv.conf contains:
```
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 185.12.64.1
nameserver 185.12.64.2
nameserver 2606:4700:4700::1111
```
Relevant section from /etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection:
```
[ipv4]
dns=1.1.1.1;8.8.8.8;
may-fail=false
method=auto
[ipv6]
address1=2a01:4f8:c012:16f3::1/64
dns=2606:4700:4700::1111;
gateway=fe80::1
may-fail=false
method=manual
```
To ensure only the explicitly …
> Prevent Hetzner default nameservers from being added to /etc/resolv.conf

- README.md
I've added tool installation commands for yay (Arch Linux) as an alternative to brew (referring to #1802).
Furthermore there's now a table of contents of the high-level headings for finding things much faster in the README, because at this point the README is pretty huge.  
If not wanted, however, I will revert that commit.
> Add installation commands & TOC to README

- templates/autoscaler.yaml.tpl
Moved volumeattachments resource to storage.k8s.io api group according to https://github.com/kubernetes/autoscaler/pull/7904
> fixes autoscaler resource permissions

- locals.tf
Reverts kube-hetzner/terraform-hcloud-kube-hetzner#1882
> Revert "fix: add tolerations to Cilium Operator for cloud provider initialization taint"

- kube.tf.example
First off, many thanks for this amazing project, it's truly a great tool that caters to the vast majority of people that use / migrate to Hetzner imo.
I added the cert_manager_version since it was missing from the example but I am thinking we should also probably provide a warning that pinning is a good idea since cert-manager introduces breaking changes across their versions. It just happened to me these last few days.
If this is enough though we can just leave it as is.
> Added cert_manager_version var in kube.tf.example
