kube-hetzner/terraform-hcloud-kube-hetzner

- locals.tf
- main.tf
- providers.tf
- variables.tf
This should lead to better readability.
> Reorganize structure of Terraform manifests

- .github/workflow/terraform.yaml
This allows you to automatically test your Terraform manifests, based on GitHub Actions.
> Add workflow for Github Actions

- agents.tf
- master.tf
- servers.tf
- variables.tf
Reverts kube-hetzner/kube-hetzner#22
> Revert "make private key optional to support hardware tokens for SSH"

- locals.tf
- main.tf
- terraform.tfvars.example
- variables.tf
Hey folks, this is to close https://github.com/kube-hetzner/kube-hetzner/issues/64. In the example, we open a port for Postgres :)
> Extra firewall rules

- modules/host/locals.tf
- modules/host/main.tf
This build upon https://github.com/kube-hetzner/kube-hetzner/pull/120.
After I saw this:
I decided that:
With a length 3, and limited to alphabetical lower case. It gives us 17576 possibilities while staying super easy to remember and to type.
> Random string node

- modules/host/main.tf
Hey folks, here's why am doing so, please let me know if I am wrong. https://www.loom.com/share/ed1de222a9364f44af0723b150f29577
> Reducing the keepers list

- modules/host/main.tf
- modules/host/versions.tf
> Replace deprecated template provider with cloudinit

- agents.tf
- control_planes.tf
- locals.tf
- main.tf
- terraform.tfvars.example
- variables.tf
Folks, this fixes the placement group limitation and uses the method proposed by @HenkVanMaanen in #142.
> Placement group fix

- init.tf
- locals.tf
- templates/calico.yaml.tpl
- templates/ccm.yaml.tpl
> Add private CIDR for calico

- terraform.tfvars.example
- variables.tf
> completed k3s channel list

- README.md
- init.tf
- templates/cert-manager.yaml.tpl
- templates/rancher.yaml.tpl
- terraform.tfvars.example
- variables.tf
This adds both cert-manager and rancher!
> Rancher addon

- control_planes.tf
- init.tf
- terraform.tfvars.example
- variables.tf
> added registration on rancher server by manifest

- main.tf
solves #190 
using kubeconfig.yaml from project-root folder works here.;)
> fix lb not being destroy if used as module

- .github/workflows/generate-docs.yaml
- .gitignore
- .terraform-docs.yml
- README.md
- docs/terraform.md
> added autogen of terraform docs

- agents.tf
- control_planes.tf
- init.tf
- kube.tf.example
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
Implements https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/224.
> added support for reserve dns domain setting

- kube.tf.example
- locals.tf
- variables.tf
> added a flag to optionally block icmp in traffic at the firewall level

- .github/workflows/validate-terraform.yaml
- modules/host/locals.tf
- modules/host/main.tf
Currently only the main directory is being linted. This will make sure
that the whole project is formatted nicely
> Check for formatting in subdirectories

- control_planes.tf
- init.tf
- kube.tf.example
- locals.tf
- modules/host/locals.tf
- modules/host/main.tf
- templates/cilium.sh.tpl
- variables.tf
Cilium offers some fantastic observability functionality I would like to
take advantage of, along side DNS based filtering in network policies
> Add cilium

- init.tf
this is being generated as a nested list, which is incorrect
Relates-to: #256
> fix tls-san value

- README.md
- agents.tf
- control_planes.tf
- docs/terraform.md
- init.tf
- kube.tf.example
- kubeconfig.tf
- kustomization_backup.tf
- locals.tf
- modules/host/main.tf
- modules/host/templates/userdata.yaml.tpl
- modules/host/variables.tf
- variables.tf
Reverts kube-hetzner/terraform-hcloud-kube-hetzner#279
> Revert "Allow setting alternative SSH port for host access"

- locals.tf
> Fix longhorn volumes

- main.tf
- output.tf
Fixes: #293.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> Allow use of load balancer even if traefik is disabled

- docs/terraform.md
- output.tf
First of all a word of thanks, this is project is awesome!
This PR simply adds the IPv6 address of the load balancer to the outputs.
> Add LB IPv6 to the outputs

- README.md
related to: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/338 and https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/311
> readme: single node setup

- README.md
- init.tf
- kube.tf.example
- templates/ccm.yaml.tpl
> Fix control plane scheduling

- autoscaler-agents.tf
- templates/autoscaler.yaml.tpl
prepend the cluster_name if set.
> Autoscaler adjustments

- agents.tf
- control_planes.tf
- modules/host/main.tf
> Various name fixes (⚠️ Almost 100% backward compatible)

- output.tf
This feature existed but somehow got lost in refactoring
> Output control plane ip as ingress

- agents.tf
- autoscaler-agents.tf
- main.tf
- scripts/cleanup.sh
This adds labels to all resources provisioned by terraform. The `cleanup.sh` is a little helper to remove all resources of a cluster if terraform has gone south (only limitation for now are CSI volumes and autoscaler nodes)
> Labels for everything

- autoscaler-agents.tf
> Fallback if no autoscaler pools are defined

- kube.tf.example
> fix spelling

- README.md
- init.tf
- kube.tf.example
- locals.tf
- templates/kured.yaml.tpl
- variables.tf
This MR adds the ability to configure kured with additional options (and override defaults)
> Add options kured

- kube.tf.example
- variables.tf
> Revert change of opensuse microos mirror

- README.md
- init.tf
- kube.tf.example
- locals.tf
- main.tf
- variables.tf
Since [pull request 590](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/590) is without any updates. Decided to fix issues opening own pull request
> Custom CIDR

- kube.tf.example
> Hcloud token env 2

- agents.tf
- control_planes.tf
- kube.tf.example
- locals.tf
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
I was missing a function to enable automatic backups in Hetzner, so here it is :)
Is it possible to make variables optional? I started using terraform a week ago and i couldn't find an option for that.
> Added backup option for hcloud servers

- agents.tf
- control_planes.tf
- docs/terraform.md
- init.tf
- kube.tf.example
- locals.tf
- modules/host/locals.tf
- modules/host/main.tf
- modules/host/templates/userdata.yaml.tpl
- templates/autoscaler-cloudinit.yaml.tpl
- variables.tf
Fix for #623. 
@kube-hetzner/core FYI have a look, there are a few changes.
> Fix private interface and dns

- locals.tf
> Fixed proxy protocol

- agents.tf
- control_planes.tf
- kube.tf.example
- locals.tf
Issue was mentioned in this discussion https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/641.
> Fix placement group error for more than 10 nodes

- agents.tf
- control_planes.tf
- init.tf
As discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/641. 
FYI @sshcherbinin
> Further tweaks to placement group

- README.md
Fixes the link to the Cilium Helm values
> Fix link to Cilium Helm values

- modules/host/main.tf
- scripts/cleanup.sh
> Fixed miscellaneous issues

- docs/terraform.md
- kube.tf.example
- locals.tf
> Enabling vault csi provider integration

- locals.tf
@mysticaltech found some missing permissions.
> missing file/folder permissions for local-path-provisioner

- kube.tf.example
- modules/host/versions.tf
- versions.tf
> Added requirement for newer functional hcloud provider

- README.md
- data.tf
- docs/terraform.md
- kube.tf.example
- locals.tf
- variables.tf
data "github_release" "..." can be skipped for those resources which are disabled by the user.
> Fix/optional skip GitHub hetzner

- init.tf
Fixed one newly introduced bug, now the code is verified to work.
> Fix/optional skip GitHub hetzner 2

- .github/workflows/generate-docs.yaml
> Revert: Update generate-docs.yaml - Bypass branch protection

- .github/workflows/generate-docs.yaml
> Update generate-docs.yaml - Moved to staging, removed beta

- README.md
- packer-template/hcloud-microos-snapshots.pkr.hcl
- scripts/create.sh
fix for #835
hcloud plugin is not an default packer plugin anymore
> add support for packer >= 1.9.0

- locals.tf
- variables.tf
Default is 1.1.1.1, but if you use a proxy, you may want to ping the proxy instead.
> feat: added variable for ping address

- examples/kustmoization_user_deploy/Readme.md
- examples/kustmoization_user_deploy/extra-manifests/cert-manager-webhook-inwx.yaml.tpl
- examples/kustmoization_user_deploy/extra-manifests/kustomization.yaml.tpl
- examples/kustmoization_user_deploy/extra-manifests/some-random-name.yaml.tpl
- kube.tf.example
a HelmChart and HelmChartConfig
Sorry for the "trailing white space removals", I hope this not a problem.
I think this can help other Kustomize noobs like me.
> Example with extra_kustomize_deployment_commands

- README.md
- agents.tf
- autoscaler-agents.tf
- control_planes.tf
- docs/terraform.md
- init.tf
- locals.tf
- output.tf
- variables.tf
fixes #949 by
- ~adding documentation about how to backup~
- making k3s_token manually overwritable
> Possibility to set k3s_token manually for restoring a cluster

- init.tf
I have gotten the newest release from here: https://github.com/hetznercloud/csi-driver
> Update hetzner-csi version

- packer-template/hcloud-microos-snapshots.pkr.hcl
Add mtr to packer template. Closes #971
> Add mtr to packer template

- variables.tf
As per @mysticaltech 's comment, the validation check was broken.
> fix: validation of var.existing_network_id repaired.

- control_planes.tf
- locals.tf
Thanks to @mraerino for the original implementation I just did the error handling
Original PR
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/881#issue-1795512839
> fix: dynamic k3s configuration for control planes

- .github/workflows/lint_pr.yaml
Besides having a pre-commit, it doesn't help if not everyone has it :))
Anyways here are the linters it auto comments on the pr if there is something as well.
> feat: add linter workflow

- autoscaler-agents.tf
- packer-template/hcloud-microos-snapshots.pkr.hcl
- variables.tf
> Replaced old image download links with working ones

- autoscaler-agents.tf
- docs/terraform.md
- kube.tf.example
- templates/autoscaler.yaml.tpl
- variables.tf
@mysticaltech it has backwards compatibility now :)
Also added a warning in the docs. Since it depends on an external party ;]
> feat: taints and labels per autoscaler nodepool

- control_planes.tf
- docs/terraform.md
- kube.tf.example
- locals.tf
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
Works for existing clusters as well!
> feat: zram support

- docs/terraform.md
- locals.tf
Apparently "none" is also possible
> fix: undefined ingress key

- variables.tf
Fix for the bug I found and reported in #1071
> Corrected error message for clashing control_plane_nodepools name

- kube.tf.example
Closes: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1074
> fix: autoscaler label example

- versions.tf
> bounded github module version, because the latest version is broken

- kube.tf.example
Comment in kube.tf diverged from default value in variables.tf
> Fix default k3s version in kube.tf

- kube.tf.example
- variables.tf
> Fix ipv6 dns resolution

- kube.tf.example
- variables.tf
> fix: Kubelet args examples, and set the same as defaults

- locals.tf
Fixing this deprecation warning:
> Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> Upgrade kustomization

- init.tf
- kustomization_user.tf
> Fix for flawed user kustomization

- kustomization_user.tf
fix typo in kustomziation_user.tf
> fix typo in kustomziation_user.tf

- README.md
- scripts/cleanup.sh
- scripts/create.sh
tofu is a fork of terraform. Maybe it would be good, for the future to use it or just support both of them.
> Added basic tofu support

- kube.tf.example
- locals.tf
> Fixes cilium selinux issues

- init.tf
- kube.tf.example
- locals.tf
- values-export.tf
> Fix ingress namespace not applied

- control_planes.tf
Fixes #1154, tip contributed by @Dullaz.
> Fix missing mkdir for all control plane nodes

- scripts/create.sh
Hi all,
I want to be able to execute create.sh non-interactive (using already set env-Variables). So I added some Checks in Variables are empty or not if if not just using them instead of reading them from CLI.
> Add posibility to run create.sh unattended

- agents.tf
- kube.tf.example
- variables.tf
Addresses https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1172
> feat: flag for enable iscsid regardless of longhorn settings.

- README.md
> Add opentofu reference to readme

- locals.tf
See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/697#issuecomment-1961356577
> Adding missing selinux rules

- .github/workflows/generate-docs.yaml
> ci: fix generate docs not running on master

- .github/workflows/generate-docs.yaml
> Allow submission of the new generated terraform docs via PR

- kube.tf.example
- locals.tf
> Fix traefik https redirect

- locals.tf
Addressing new SELinux rules needed for https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/697#issuecomment-1971980790
> Added Selinux Rules

- scripts/create.sh
Something that should have been included in: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1192
> Update Terraform install notification in create.sh

- README.md
Added the mention to get this into the wild, it's too useful to not share.
> Mention of KH Assistant Custom GPT

- locals.tf
> Fix missing SELinux rules

- autoscaler-agents.tf
- kube.tf.example
- variables.tf
Subsequent to #1282 and #1278. 
@UBaggeler FYI, small tweaks, especially moved from type string for the var to number. Thanks again for the help and contributions! Never hesitate 🙏
> Tweak autoscaler creation timeout

- locals.tf
There policy changes are need to make fluentbit to work on cluster
> sepolicy changes for fluentbit

- README.md
- docs/terraform.md
- kube.tf.example
- locals.tf
- variables.tf
This PR adds option to enable Hubble for the Cilium CNI without using `cilium_values`.
> feat: Add option to enable Hubble

- agents.tf
- control_planes.tf
- docs/terraform.md
- modules/host/main.tf
- modules/host/variables.tf
- variables.tf
Add variable to support keeping OS disk size the same when resizing nodes as discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1344
> Keep OS disk size

- kube.tf.example
- variables.tf
Closing #1364
Nothing fancy, just upgrading the version and moving back to the mother repo as the changes by @Silvest89 have been merged. Tested it, all good.
> Updated cluster-autoscaler

- kube.tf.example
- kubeconfig.tf
- variables.tf
> Make kubeconfig_server_address configurable

- kube.tf.example
Fix for https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1398
> improve documentation about etcd snapshot parameters

- init.tf
- locals.tf
- templates/cert_manager.yaml.tpl
- templates/csi-driver-smb.yaml.tpl
- templates/longhorn.yaml.tpl
- templates/rancher.yaml.tpl
- variables.tf
fixes #1414 and #1413 
builds upon https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/1411
> Helmchart version and bootstrap

- locals.tf
> make is_single_node_cluster depend on autoscaler_nodepools too

- locals.tf
> Fix autoscaler_max_count computation for disabled cluster autoscaler feature

- init.tf
- kube.tf.example
- locals.tf
- templates/plans.yaml.tpl
- variables.tf
Reverts kube-hetzner/terraform-hcloud-kube-hetzner#1436
> Revert "Allows specifying k3s version"

- variables.tf
> Switched the autoscaler image to hetzner's own

- variables.tf
> Fix: Revert back to Kubernetes community autoscaler

- locals.tf
> Drying-up locals.tf after direct k3s version support

- locals.tf
> New system upgrade controller manifest

- locals.tf
Removed uneeded kustomization patch for system-upgrade-controller
> Fix System Upgrade Controller

- autoscaler-agents.tf
- locals.tf
- modules/host/locals.tf
- modules/host/main.tf
- modules/host/templates/cloudinit.yaml.tpl
- templates/autoscaler-cloudinit.yaml.tpl
Fixes #1422
@tobiasehlert I like that, your solution is elegant. Please can you confirm that it works?
> fix: dns configuration with cloud-init

- README.md
> Update README.md to correct KH Assistant link

- locals.tf
And include `append` permission.
> SELinux: sync container_var_lib_t:file & var_lib_t:file

- README.md
> [docs] updated postinstall_exec command for restore

- autoscaler-agents.tf
- control_planes.tf
- init.tf
- kustomize/flannel-rbac.yaml
- locals.tf
- scripts/cleanup.sh
- versions.tf
This PR introduces a few changes:
- Adds Flannel RBAC configuration and updates locals for conditional inclusion. Fixes #1714
- Updates the required Terraform version to 1.8.0.
> Feat: Flannel RBAC and other improvements

- locals.tf
> Fix hardcoded eth0

- docs/llms.md
- Comprehensive update to llms.md documentation to reflect all new variables and features added since June 2025
- Documents approximately 35 new configuration options that were previously undocumented
- Improves organization and clarity for LLM deployment configurations
This PR updates the llms.md documentation file to include:
- NAT router functionality and IPv6 support configuration
- Rancher integration options and parameters
- Kustomization control features and Helm values override options
- System upgrade controller, snapshot controller, and CSI driver configurations
- Advanced options for autoscaler, network policies, placement groups, and more
- Improved organization with clear sections for different feature sets
Used Gemini CLI to systematically compare kube.tf.example with …
> docs: update llms.md with new configuration options
